### ISSUE TITLE
Add script to get time at a location

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/utility-bash-scripts#7]
I have no clue how to do this but it's a good script idea, hence opening an issue. 

We can have a script that takes in place info (example - `PST`, `Chicago`, `London`) and gives the current time in that location. One way to do it could be scraping Google or using a REST API but there could be native language libraries that do this too.

#5

**Comment by pitasi** [comment]
I wish I had time to make a PR for the hacktoberfest but as a starting point:

`TZ='America/Los_Angeles' date`

something like this works. More options available in the `date` man page :)

**Comment by pitasi** [comment]
At last I found some minutes to write a couple of new scripts, including "clock". Merging #11 should close this issue :smile:
